// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1WhpNlkA-flyqpzby4pLvzelBkfECHJ0',
    appId: '1:199703031145:web:28c9f2bcc1a55ce2e861f8',
    messagingSenderId: '199703031145',
    projectId: 'todo-5e5e8',
    authDomain: 'todo-5e5e8.firebaseapp.com',
    storageBucket: 'todo-5e5e8.appspot.com',
    measurementId: 'G-3V2KWQSKJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgDqt8GVgYbsD0bZmn9dZEyzpm5JKLiw',
    appId: '1:199703031145:android:e6cbb0bd3bd6c987e861f8',
    messagingSenderId: '199703031145',
    projectId: 'todo-5e5e8',
    storageBucket: 'todo-5e5e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU9lRsFI0BeaLJTTr_DZ7AkF6sLKhfhxA',
    appId: '1:199703031145:ios:dc347ee35efdf4e8e861f8',
    messagingSenderId: '199703031145',
    projectId: 'todo-5e5e8',
    storageBucket: 'todo-5e5e8.appspot.com',
    iosClientId: '199703031145-mlu0o1813f6ibq5u0civ093v3qcqblrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU9lRsFI0BeaLJTTr_DZ7AkF6sLKhfhxA',
    appId: '1:199703031145:ios:b54c33c4ebbd9cf1e861f8',
    messagingSenderId: '199703031145',
    projectId: 'todo-5e5e8',
    storageBucket: 'todo-5e5e8.appspot.com',
    iosClientId: '199703031145-2jnb3kbvd0duel0r6ta370342621cd7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo3.RunnerTests',
  );
}
